### ISSUE TITLE
“写下你的评论”bug

### ISSUE THREAD

**Issue by icyfox-bupt** [xw2423/nForum#15]
IE8在快捷回复栏直接输入头像会出现此bug

现在满byr都是这样的字句了。

不知道是不是这里的bug，还是论坛前端自己改的

**Comment by wdjwxh** [comment]
输入头像是什么意思？

**Comment by icyfox-bupt** [comment]
在`看帖页面` --> `快捷回复`-->`插入一个表情` 看效果

**Comment by wdjwxh** [comment]
收到，我去看下.
